version: "3.1"

#healthcheck:
#    test: ["CMD", "curl", "-f", "http://localhost"]
#    interval: 5s
#    timeout: 5s
#    retries: 3
#    start_period: 5s

services: 
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1236
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    messenger-server:
        image: docker-messenger
        restart: 'no'
        ports: 
            - 8000:8000 #right: container side
#        environment:
#            DB_USER: root
#            DB_PASSWORD: 1236
#            DB_HOST: db
#            DB_PORT: 3306
#            FA_DOCKS_URL: /swagger

